export const Constants = {
  typeImages : [
    { value: "prec", label: "Precipitación"},
    { value: "tmax", label: "Temperatura Máxima"},
    { value: "tmin", label: "Temperatura Mínima"}
  ],
  months: [
    { value: "01", label: "Enero"},
    { value: "02", label: "Febero"},
    { value: "03", label: "Marzo"},
    { value: "04", label: "Abril"},
    { value: "05", label: "Mayo"},
    { value: "06", label: "Junio"},
    { value: "07", label: "Julio"},
    { value: "08", label: "Agosto"},
    { value: "09", label: "Setiembre"},
    { value: "10", label: "Octubre"},
    { value: "11", label: "Noviembre"},
    { value: "12", label: "Diciembre"},
  ],
  year: [
    { label: "2020", value: "2020" },
    { label: "2021", value: "2021" }
  ],
  bestCities: [
    "Brazil, Bahia, Jequié, Boacu",
    "Brazil, Bahia, Jequié, Monte Branco",
    "Brazil, Bahia, Lafaiete Coutinho, Lafaiete Coutinho",
    "Brazil, Bahia, Lajedo do Tabocal, Lajedo do Tabocal",
    "Brazil, Bahia, Ibicuí, Ibitupa",
    "Brazil, Bahia, Poções, Poções",
    "Brazil, Bahia, Boa Nova, Boa Nova",
    "Brazil, Bahia, Aiquara, Aiquara",
    "Brazil, Bahia, Poções, Poções",
    "Brazil, Bahia, Barra da Choça, Barra do Choca",
    "Brazil, Bahia, Caatiba, Caatiba",
    "Brazil, Bahia, Vitória da Conquista, Vitória da Conquista",
    "Brazil, Bahia, Vitória da Conquista, Igua",
    "Brazil, Bahia, Belo Campo, Belo Campo",
    "Brazil, Bahia, Vitória da Conquista, Veredinha",
    "Brazil, Bahia, Belo Campo, Belo Campo",
    "Brazil, Bahia, Vitória da Conquista, Cercadinho",
    "Brazil, Bahia, Ribeirão do Largo, Ribeirão do Largo",
    "Brazil, Bahia, Jeremoabo, Jiquiriçá",
    "Brazil, Bahia, Brejões, Brejões",
    "Brazil, Bahia, Piraí do Norte, Piraí do Norte",
    "Brazil, Bahia, Ibirapitanga, Ibirapitanga",
    "Brazil, Bahia, Aurelino Leal, Aurelino Leal",
    "Brazil, Bahia, Uruçuca, Uruçuca",
    "Brazil, Bahia, Itapitanga, Itapitanga",
    "Brazil, Bahia, Itagibá, Itagibá",
    "Brazil, Bahia, Manoel Vitorino, Manoel Vitorino",
    "Brazil, Bahia, Jequié, Boacu",
    "Brazil, Bahia, Jequié, Monte Branco",
    "Brazil, Bahia, Planaltino, Nova Itaipe",
    "Brazil, Bahia, Nova Itarana, Nova Itarana",
    "Brazil, Bahia, Brejões, Brejões",
    "Brazil, Bahia, Santo Antônio de Jesus, Santo Antônio de Jesus",
    "Brazil, Bahia, Presidente Tancredo Neves, Presidente Tancredo Neves",
    "Brazil, Bahia, Ibirapitanga, Ibirapitanga",
    "Brazil, Bahia, Itagi, Itagi",
    "Brazil, Bahia, Itapitanga, Itapitanga",
    "Brazil, Bahia, Itapé, Itapé"
  ],
  infoBestCities: [
    "Brazil, Bahia, Jequié, Boacu",
    "Brazil, Bahia, Jequié, Monte Branco",
    "Brazil, Bahia, Lafaiete Coutinho, Lafaiete Coutinho",
    "Lajedo do Tabocal está ubicado en la Serra do Sincorá, una cadena montañosa en el interior de Bahía. La ciudad tiene un clima tropical húmedo. Lajedo do Tabocal es el hogar de la Cachoeira do Tabuleiro, una hermosa cascada de 42 metros de altura. La ciudad también alberga el Festival de Lajedo do Tabocal, un evento anual que celebra la cultura y la música baiana.",
    "Brazil, Bahia, Ibicuí, Ibitupa",
    "Brazil, Bahia, Poções, Poções",
    "Brazil, Bahia, Boa Nova, Boa Nova",
    "Brazil, Bahia, Aiquara, Aiquara",
    "Brazil, Bahia, Poções, Poções",
    "Brazil, Bahia, Barra da Choça, Barra do Choca",
    "Brazil, Bahia, Caatiba, Caatiba",
    "Brazil, Bahia, Vitória da Conquista, Vitória da Conquista",
    "Brazil, Bahia, Vitória da Conquista, Igua",
    "Brazil, Bahia, Belo Campo, Belo Campo",
    "Brazil, Bahia, Vitória da Conquista, Veredinha",
    "Brazil, Bahia, Belo Campo, Belo Campo",
    "Brazil, Bahia, Vitória da Conquista, Cercadinho",
    "Brazil, Bahia, Ribeirão do Largo, Ribeirão do Largo",
    "Brazil, Bahia, Jeremoabo, Jiquiriçá",
    "Brazil, Bahia, Brejões, Brejões",
    "Brazil, Bahia, Piraí do Norte, Piraí do Norte",
    "Brazil, Bahia, Ibirapitanga, Ibirapitanga",
    "Brazil, Bahia, Aurelino Leal, Aurelino Leal",
    "Brazil, Bahia, Uruçuca, Uruçuca",
    "Brazil, Bahia, Itapitanga, Itapitanga",
    "Brazil, Bahia, Itagibá, Itagibá",
    "Brazil, Bahia, Manoel Vitorino, Manoel Vitorino",
    "Boaçu está ubicado en la costa del océano Atlántico. La ciudad tiene un clima tropical cálido y húmedo. Boaçu es el hogar de la Praia de Boaçu, una hermosa playa de arena blanca y aguas cristalinas. La ciudad también alberga el Festival de Boaçu, un evento anual que celebra la cultura y la música baiana.",
    "Monte Branco está ubicado en la Serra do Sincorá, una cadena montañosa en el interior de Bahía. La ciudad tiene un clima tropical húmedo. Monte Branco es el hogar de la Cachoeira do Monte Branco, una hermosa cascada de 30 metros de altura. La ciudad también alberga el Festival de Monte Branco, un evento anual que celebra la cultura y la música baiana.",
    "Brazil, Bahia, Planaltino, Nova Itaipe",
    "Brazil, Bahia, Nova Itarana, Nova Itarana",
    "Brazil, Bahia, Brejões, Brejões",
    "Brazil, Bahia, Santo Antônio de Jesus, Santo Antônio de Jesus",
    "Brazil, Bahia, Presidente Tancredo Neves, Presidente Tancredo Neves",
    "Brazil, Bahia, Ibirapitanga, Ibirapitanga",
    "Brazil, Bahia, Itagi, Itagi",
    "Brazil, Bahia, Itapitanga, Itapitanga",
    "Brazil, Bahia, Itapé, Itapé"
  ]
}
