export const Constants = {
  typeImages : [
    { value: "prec", label: "Precipitación"},
    { value: "tmax", label: "Temperatura Máxima"},
    { value: "tmin", label: "Temperatura Mínima"}
  ],
  months: [
    { value: "01", label: "Enero"},
    { value: "02", label: "Febero"},
    { value: "03", label: "Marzo"},
    { value: "04", label: "Abril"},
    { value: "05", label: "Mayo"},
    { value: "06", label: "Junio"},
    { value: "07", label: "Julio"},
    { value: "08", label: "Agosto"},
    { value: "09", label: "Setiembre"},
    { value: "10", label: "Octubre"},
    { value: "11", label: "Noviembre"},
    { value: "12", label: "Diciembre"},
  ],
  year: [
    { label: "2020", value: "2020" },
    { label: "2021", value: "2021" }
  ],
  bestCities: [
    "Brazil, Bahia, Jequié, Boacu",
    "Brazil, Bahia, Jequié, Monte Branco",
    "Brazil, Bahia, Lafaiete Coutinho, Lafaiete Coutinho",
    "Brazil, Bahia, Lajedo do Tabocal, Lajedo do Tabocal",
    "Brazil, Bahia, Ibicuí, Ibitupa",
    "Brazil, Bahia, Boa Nova, Boa Nova",
    "Brazil, Bahia, Aiquara, Aiquara",
    "Brazil, Bahia, Poções, Poções",
    "Brazil, Bahia, Barra da Choça, Barra do Choca",
    "Brazil, Bahia, Caatiba, Caatiba",
    "Brazil, Bahia, Vitória da Conquista, Vitória da Conquista",
    "Brazil, Bahia, Vitória da Conquista, Igua",
    "Brazil, Bahia, Vitória da Conquista, Veredinha",
    "Brazil, Bahia, Belo Campo, Belo Campo",
    "Brazil, Bahia, Vitória da Conquista, Cercadinho",
    "Brazil, Bahia, Ribeirão do Largo, Ribeirão do Largo",
    "Brazil, Bahia, Jeremoabo, Jiquiriçá",
    "Brazil, Bahia, Piraí do Norte, Piraí do Norte",
    "Brazil, Bahia, Aurelino Leal, Aurelino Leal",
    "Brazil, Bahia, Uruçuca, Uruçuca",
    "Brazil, Bahia, Itagibá, Itagibá",
    "Brazil, Bahia, Manoel Vitorino, Manoel Vitorino",
    "Brazil, Bahia, Jequié, Boacu",
    "Brazil, Bahia, Jequié, Monte Branco",
    "Brazil, Bahia, Planaltino, Nova Itaipe",
    "Brazil, Bahia, Nova Itarana, Nova Itarana",
    "Brazil, Bahia, Brejões, Brejões",
    "Brazil, Bahia, Santo Antônio de Jesus, Santo Antônio de Jesus",
    "Brazil, Bahia, Presidente Tancredo Neves, Presidente Tancredo Neves",
    "Brazil, Bahia, Ibirapitanga, Ibirapitanga",
    "Brazil, Bahia, Itagi, Itagi",
    "Brazil, Bahia, Itapitanga, Itapitanga",
    "Brazil, Bahia, Itapé, Itapé"
  ],
  infoBestCities: [
    "Boaçu es un pueblo pequeño y tranquilo ubicado en la costa del océano Atlántico, en el estado de Bahía, Brasil. Es conocido por sus hermosas playas, su exuberante vegetación y su rica cultura. La playa más popular de Boaçu es la Praia de Boaçu, una hermosa playa de arena blanca y aguas cristalinas. La playa es un popular destino para nadar, tomar el sol y practicar deportes acuáticos. Boaçu también es un destino popular para los amantes de la naturaleza. La ciudad está rodeada de exuberantes bosques y montañas, que ofrecen oportunidades para caminatas, ciclismo y observación de aves. Además de sus hermosas playas y su exuberante vegetación, Boaçu también es un destino cultural. La ciudad alberga el Festival de Boaçu, un evento anual que celebra la cultura y la música baiana. El festival presenta música, danza, comida y artesanías tradicionales de Bahía.",
    "Monte Branco es un pequeño pueblo ubicado en la Serra do Sincorá, una cadena montañosa en el interior de Bahía. Es conocido por sus exuberantes bosques, sus cascadas y su rica cultura. La cascada más popular de Monte Branco es la Cachoeira do Monte Branco, una hermosa cascada de 30 metros de altura. La cascada es un popular destino para nadar, tomar el sol y practicar deportes acuáticos. Monte Branco también es un destino popular para los amantes de la naturaleza. La ciudad está rodeada de exuberantes bosques, que ofrecen oportunidades para caminatas, ciclismo y observación de aves. Además de sus exuberantes bosques y cascadas, Monte Branco también es un destino cultural. La ciudad alberga el Festival de Monte Branco, un evento anual que celebra la cultura y la música baiana. El festival presenta música, danza, comida y artesanías tradicionales de Bahía.",
    "Lafaiete Coutinho es un pueblo ubicado en el valle del río Paraguaçu, rodeado de exuberantes bosques y montañas. Es conocido por sus grutas, cascadas y su rica cultura. La gruta más popular de Lafaiete Coutinho es la Gruta da Lapinha, una cueva de piedra caliza con estalactitas y estalagmitas. La gruta es un popular destino para los visitantes que buscan explorar la belleza natural de Bahía. Lafaiete Coutinho también es un destino popular para los amantes de la naturaleza. La ciudad está rodeada de exuberantes bosques, que ofrecen oportunidades para caminatas, ciclismo y observación de aves. Además de sus grutas y cascadas, Lafaiete Coutinho también es un destino cultural. La ciudad alberga el Festival de Lafaiete Coutinho, un evento anual que celebra la cultura y la música baiana. El festival presenta música, danza, comida y artesanías tradicionales de Bahía.",
    "Lajedo do Tabocal está ubicado en la Serra do Sincorá, una cadena montañosa en el interior de Bahía. La ciudad tiene un clima tropical húmedo. Lajedo do Tabocal es el hogar de la Cachoeira do Tabuleiro, una hermosa cascada de 42 metros de altura. La ciudad también alberga el Festival de Lajedo do Tabocal, un evento anual que celebra la cultura y la música baiana.",
    "Ibicuí es una ciudad ubicada en el estado de Bahía, Brasil. Es conocido por sus cascadas, ríos y bosques. La cascada más popular de Ibicuí es la Cachoeira do Poço do Diabo, una hermosa cascada de 40 metros de altura. La cascada es un popular destino para los visitantes que buscan explorar la belleza natural de Bahía. Ibicuí también es un destino popular para los amantes de la naturaleza. La ciudad está rodeada de exuberantes bosques, que ofrecen oportunidades para caminatas, ciclismo y observación de aves. Además de sus cascadas, ríos y bosques, Ibicuí también es un destino cultural. La ciudad alberga el Festival de Ibicuí, un evento anual que celebra la cultura y la música baiana. El festival presenta música, danza, comida y artesanías tradicionales de Bahía.",
    "Boa Nova es una ciudad ubicada en el estado de Bahía, Brasil. Es conocido por sus cascadas, ríos y bosques. La cascada más popular de Boa Nova es la Cachoeira do Poço do Paraíso, una hermosa cascada de 30 metros de altura. La cascada es un popular destino para los visitantes que buscan explorar la belleza natural de Bahía. Boa Nova también es un destino popular para los amantes de la naturaleza. La ciudad está rodeada de exuberantes bosques, que ofrecen oportunidades para caminatas, ciclismo y observación de aves. Además de sus cascadas, ríos y bosques, Boa Nova también es un destino cultural. La ciudad alberga el Festival de Boa Nova, un evento anual que celebra la cultura y la música baiana. El festival presenta música, danza, comida y artesanías tradicionales de Bahía.",
    "Aiquara es una ciudad ubicada en el estado de Bahía, Brasil. Es conocido por sus cascadas, ríos, bosques y su rica cultura. La cascada más popular de Aiquara es la Cachoeira do Brumado, una hermosa cascada de 20 metros de altura. La cascada es un popular destino para los visitantes que buscan explorar la belleza natural de Bahía. Aiquara también es un destino popular para los amantes de la naturaleza. La ciudad está rodeada de exuberantes bosques, que ofrecen oportunidades para caminatas, ciclismo y observación de aves. Además de sus cascadas, ríos y bosques, Aiquara también es un destino cultural. La ciudad alberga el Festival de Aiquara, un evento anual que celebra la cultura y la música baiana. El festival presenta música, danza, comida y artesanías tradicionales de Bahía.",
    "Poções es una ciudad en el estado de Bahía, Brasil. Se encuentra a unos 400 kilómetros de la capital del estado, Salvador. Poções es un destino popular para los amantes de la naturaleza, ya que está rodeada de exuberantes bosques y montañas. La ciudad también alberga varios festivales culturales, como el Festival de Poções, que celebra la música y la danza baiana.",
    "Barra do Choca es conocida como la Capital del Café debido a su clima y suelo ideales para el cultivo del café. La ciudad también es un destino popular para los amantes de la naturaleza, ya que está rodeada de exuberantes bosques y cascadas.",
    "Caatiba es conocida como la Ciudad de la Piedra debido a sus numerosos afloramientos rocosos. La ciudad también es un destino popular para los amantes de la naturaleza, ya que está rodeada de exuberantes bosques y cascadas.",
    "Vitória da Conquista es una ciudad brasileña ubicada en el estado de Bahía. Es la tercera ciudad más grande del estado, con una población de más de 370.000 habitantes. La ciudad está situada en el interior de Bahía, a unos 500 kilómetros de la capital, Salvador. Vitória da Conquista es un importante centro comercial y de transporte. La ciudad es un importante productor de café, cacao y otros productos agrícolas. Vitória da Conquista también es un importante centro cultural. La ciudad alberga varios museos, teatros y galerías de arte.",
    "Iguaí es un municipio brasileño ubicado en el estado de Bahía. Se encuentra a unos 200 kilómetros de Vitória da Conquista y a 600 kilómetros de Salvador. La ciudad está situada en el interior de Bahía, a orillas del río Gongogi. Iguaí es conocida por sus cascadas, ríos y bosques. La ciudad es un destino popular para los amantes de la naturaleza.",
    "Veredinha es un distrito de la ciudad de Vitória da Conquista, en el estado de Bahía, Brasil. Se encuentra a unos 9 kilómetros del centro de la ciudad, en la Serra do Sincorá. Veredinha es conocida por sus hermosas cascadas y ríos. La ciudad es un destino popular para los amantes de la naturaleza.",
    "Belo Campo es un municipio brasileño del estado de Bahía. Se encuentra a unos 100 kilómetros de Vitória da Conquista y a 600 kilómetros de Salvador. La ciudad está situada en el interior de Bahía, en la Serra do Sincorá.Brazil, Bahia, Belo Campo, Belo Campo",
    "Cercadinho es un pequeño pueblo ubicado a unos 20 kilómetros de Vitória da Conquista, en el estado de Bahía, Brasil. La ciudad se encuentra en la Serra do Sincorá, una cordillera que atraviesa el interior del estado.",
    "Ribeirão do Largo es un municipio brasileño del estado de Bahía. Se encuentra a unos 200 kilómetros de Vitória da Conquista y a 600 kilómetros de Salvador. La ciudad está situada en el interior de Bahía, a orillas del río Ribeirão do Largo. Ribeirão do Largo es conocida por su producción de café, cacao y otros productos agrícolas. La ciudad también es un destino popular para los amantes de la naturaleza, gracias a sus hermosas cascadas y ríos.",
    "Jiquiriçá es un municipio agrícola y turístico ubicado en la región de la Chapada Diamantina. La ciudad es conocida por su producción de cacao, café y frutas. Jiquiriçá también es un destino popular para los amantes de la naturaleza, gracias a sus cascadas, ríos y bosques.",
    "Piraí do Norte es un municipio brasileño del estado de Bahía. Se encuentra a unos 320 kilómetros de Salvador y a 11 kilómetros de Gandu. La ciudad está situada en la costa de Bahía, a orillas del río Piraí do Norte. Piraí do Norte es conocida por sus playas, su historia y su cultura. La ciudad es un destino popular para los turistas que buscan relajarse y disfrutar de la belleza natural de Bahía.",
    "Aurelino Leal es un municipio brasileño del estado de Bahía, ubicado en la región de la Chapada Diamantina. Se encuentra a unos 183 kilómetros de la capital del estado, Salvador. La ciudad está situada en una zona montañosa, con un clima tropical.",
    "Uruçuca es un municipio brasileño del estado de Bahía. Se encuentra a unos 200 kilómetros de la capital del estado, Salvador. La ciudad está situada en el litoral sul de Bahía, a orillas del río Uruçuca. Uruçuca es conocida por su belleza natural, sus playas paradisíacas y su rica biodiversidad. La ciudad es un destino popular para los turistas que buscan relajarse y disfrutar de la belleza natural de Bahía.",
    "Itagibá es un municipio brasileño del estado de Bahía, ubicado en la región del sur del estado. Se encuentra a unos 270 kilómetros de la capital del estado, Salvador. La ciudad está situada en el valle del río Paraguaçu, a orillas del río Gongogi.",
    "Manoel Vitorino es un municipio brasileño del estado de Bahía. Se encuentra a unos 530 kilómetros de la capital del estado, Salvador. La ciudad está situada en el interior de Bahía, a orillas del río Manoel Vitorino. Manoel Vitorino es conocido por su producción de cacao, café y otros productos agrícolas. La ciudad también es un destino popular para los amantes de la naturaleza, gracias a sus hermosas cascadas y ríos.",
    "Boaçu está ubicado en la costa del océano Atlántico. La ciudad tiene un clima tropical cálido y húmedo. Boaçu es el hogar de la Praia de Boaçu, una hermosa playa de arena blanca y aguas cristalinas. La ciudad también alberga el Festival de Boaçu, un evento anual que celebra la cultura y la música baiana.",
    "Monte Branco está ubicado en la Serra do Sincorá, una cadena montañosa en el interior de Bahía. La ciudad tiene un clima tropical húmedo. Monte Branco es el hogar de la Cachoeira do Monte Branco, una hermosa cascada de 30 metros de altura. La ciudad también alberga el Festival de Monte Branco, un evento anual que celebra la cultura y la música baiana.",
    "Planaltino es un municipio brasileño del estado de Bahía, ubicado en la región sudoeste del estado. Se encuentra a unos 410 kilómetros de la capital del estado, Salvador. La ciudad está situada en una meseta, a orillas del río Planaltino. Nova Itaipe es un distrito del municipio de Planaltino. Se encuentra a unos 10 kilómetros de la sede municipal.",
    "Nova Itarana es un municipio brasileño del estado de Bahía. Se encuentra a unos 320 kilómetros de la capital del estado, Salvador. La ciudad está situada en la costa de Bahía, a orillas del río Piraí do Norte.  Nova Itarana es conocida por sus playas, su historia y su cultura. La ciudad es un destino popular para los turistas que buscan relajarse y disfrutar de la belleza natural de Bahía.",
    "Brejões también es un destino popular para los aficionados a la historia y la cultura. La ciudad tiene varios monumentos históricos, como iglesias y capillas. Brejões también alberga varios festivales culturales durante el año, como el Festival da Cultura do Cacau, que celebra la producción del cacao. ",
    "Santo Antônio de Jesus es conocida por sus fiestas juninas, que atraen a miles de visitantes de todo el país. La ciudad también es un destino popular para los amantes de la historia y la cultura. Santo Antônio de Jesus tiene un rico patrimonio histórico y cultural, que se refleja en sus iglesias, museos y festivales.",
    "Presidente Tancredo Neves es un municipio brasileño del estado de Bahía. Se encuentra a unos 240 kilómetros de la capital del estado, Salvador. La ciudad está situada en la región del Recôncavo Baiano, a orillas del río Paraguaçu. ",
    "Ibirapitanga es un municipio brasileño del estado de Bahía. Se encuentra a unos 350 kilómetros de la capital del estado, Salvador. La ciudad está situada en el interior de Bahía, a orillas del río Cachoeira. Ibirapitanga es conocido por su producción de cacao, café y otros productos agrícolas. La ciudad también es un destino popular para los amantes de la naturaleza, gracias a sus hermosas cascadas y ríos.",
    "Itagi es un municipio brasileño del estado de Bahía. Se encuentra a unos 200 kilómetros de la capital del estado, Salvador. La ciudad está situada en la región del Recôncavo Baiano, a orillas del río Paraguaçu. Itagi es un destino popular para los amantes de la naturaleza, gracias a sus hermosas cascadas, ríos y bosques. La ciudad también es un destino popular para los aficionados a la historia y la cultura.",
    "Itapitanga es un municipio brasileño del estado de Bahía. Se encuentra a unos 320 kilómetros de la capital del estado, Salvador. La ciudad está situada en la costa de Bahía, a orillas del río Piraí do Norte. Itapitanga es conocida por sus playas, su historia y su cultura. La ciudad es un destino popular para los turistas que buscan relajarse y disfrutar de la belleza natural de Bahía.",
    "Itapé es un municipio brasileño del estado de Bahía, ubicado en la costa sur del estado. Se encuentra a unos 430 kilómetros de la capital del estado, Salvador. La ciudad está situada a orillas del río Itapé, que desemboca en el océano Atlántico. Itapé es conocida por sus playas, sus cascadas y su naturaleza exuberante. La ciudad es un destino popular para los turistas que buscan relajarse y disfrutar de las bellezas naturales de Bahía."
  ]
}
